alias: Adjust Charging Current
description: Control EV charger current to avoid overcurrent
triggers:
  - entity_id:
      - sensor.actual_current
    trigger: state
conditions:
  - condition: state
    entity_id: sensor.charger_status_connector
    state: Charging
    enabled: true
actions:
  - data:
      value: >
        {% set min_charge_current = 6 %}
        {% set max_charge_current = 16 %}
        {% set max_total_current = states('input_number.maximum_load') | float | default(25) %}
        {% set current_charger_setting = states('number.charger_maximum_current') | float %}
        {% set measured_current = states('sensor.actual_current') | float | default(none) %}

        {% set new_current = max_total_current - measured_current + current_charger_setting %}
        {% if new_current > max_charge_current %}
          {% set new_current = max_charge_current %}
        {% endif %} {% if new_current < min_charge_current %}
          {% set new_current = min_charge_current %}
        {% endif %}

        {{ new_current | round(0, 'floor') }}
    target:
      entity_id: number.charger_maximum_current
    action: number.set_value
mode: single
max: 3
