template:
  - sensor:
      - name: "Actual Power"
        unique_id: actual_power
        state: >-
          {{ 
            [ states('sensor.main_power_channel_a_power'), 
              states('sensor.main_power_channel_b_power'),
              states('sensor.main_power_channel_c_power'),
            ] | map('float') | sum
          }}
        unit_of_measurement: W
        device_class: power
        state_class: measurement
  - sensor:
      - name: "Actual Current"
        unique_id: actual_current
        device_class: power
        state_class: measurement
        unit_of_measurement: A
        state: >
          {{
            [ states('sensor.main_power_channel_a_current'),
              states('sensor.main_power_channel_b_current'),
              states('sensor.main_power_channel_c_current'),
            ] | map('float') | max
          }}
